### PR TITLE
catch any exception thrown inside an HTTP request scenario

### LINKED ISSUE #1030: HTTP - some exception are not cached
When an exception is thrown by the HTTP router (for example in case of malformed body), the request is silently dropped and the client does never receiver an error response.
It should send a 400 or 500 response instead

### PR DESCRIPTION
**Pull request by ballinette**
catch any exception thrown inside an HTTP request scenario, and send back a response with errors

If the exception thrown is a KuzzleError, returns the given error with its status code
If not, returns a 500 error with the error message.

Also catch JSON parsing error for x-kuzzle-volatile header

fix #1030

### CODE REVIEW

File: lib/api/core/httpRouter/routeHandler.js [hunk 1]
```diff
@@ -48,7 +52,11 @@ class RouteHandler {
         this.data.jwt = headers[k].substring('Bearer '.length);
       }
       else if (k.toLowerCase() === 'x-kuzzle-volatile') {
-        this.data.volatile = JSON.parse(headers[k]);
+        try {
+          this.data.volatile = JSON.parse(headers[k]);
+        } catch (e) {
+          throw new BadRequestError('Unable to convert HTTP x-kuzzle-volatile header to JSON')
```
Comment (kuzzle) [inline lib/api/core/httpRouter/routeHandler.js]: MINOR Add a semicolon at the end of this statement. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3ASemicolon)

File: lib/api/core/httpRouter/index.js [hunk 2]
```diff
@@ -140,36 +143,45 @@ class Router {
...
       routeHandler.addContent(httpRequest.content);
       routeHandler.invokeHandler(cb);
     }
     catch (e) {
-      replyWithError(cb, routeHandler.getRequest(), new BadRequestError('Unable to convert HTTP body to JSON'));
+      if (request === undefined) {
+        request = new Request({requestId: httpRequest.requestId}, {}, 'rest');
+        request.response.setHeaders(this.defaultHeaders);
+      }
+      if (! e instanceof KuzzleError) {
```
Comment (kuzzle) [inline lib/api/core/httpRouter/index.js]: CRITICAL Add parentheses to perform "instanceof" operator before logical NOT operator. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS3812)

File: lib/api/core/httpRouter/index.js [hunk 3]
```diff
@@ -140,36 +143,45 @@ class Router {
...
+        e = new InternalError(e);
```
Comment (kuzzle) [inline lib/api/core/httpRouter/index.js]: MINOR Introduce a new variable instead of reusing the caught exception "e". [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS1226)

**Comment by kuzzle** [comment]
SonarQube analysis reported 3 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: lib/api/core/httpRouter/routeHandler.js (hunk 1 above)
Comment (kuzzle) [inline lib/api/core/httpRouter/routeHandler.js]: MINOR Add a semicolon at the end of this statement. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3ASemicolon)

File: lib/api/core/httpRouter/index.js (hunk 2 above)
Comment (kuzzle) [inline lib/api/core/httpRouter/index.js]: CRITICAL Add parentheses to perform "instanceof" operator before logical NOT operator. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS3812)

File: lib/api/core/httpRouter/index.js (hunk 3 above)
Comment (kuzzle) [inline lib/api/core/httpRouter/index.js]: MINOR Introduce a new variable instead of reusing the caught exception "e". [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS1226)
