### PR TITLE
Release 1.5.0

### LINKED ISSUE #1015: The login route does not provide the expireIn property
When the user relies on the default expireIn (doesn't provide it when calling login) it could be useful to provide it in the result. Currently it only returns the user kuid and the JWT.

### LINKED ISSUE #1115: Consistency mismatch between search and searchUser with a scroll param
When using document/search with a scroll param, the returned scroll id is available in result._scroll_id but when using security/searchUser with a scroll param, the returned scroll id is available in result.scrollId

## Expected Behavior
Scroll id should be named the same way in both

## Current Behavior
It doesn't

## Possible Solution
Rename

## Steps to Reproduce
```

$ http POST :7512/users/_search?from=0\&size=1\&scroll=30s
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Tue, 15 May 2018 12:03:32 GMT
Transfer-Encoding: chunked
content-type: application/json

{
    "action": "searchUsers",
    "collection": null,
    "controller": "security",
    "error": null,
    "index": null,
    "requestId": "5fbc7244-3a05-4575-84f3-da2f5ae52499",
    "result": {
        "hits": [
            {
               ...
            }
        ],
        "scrollId": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAADFVeFktFcERsUlhyUWx1bTNXTzgtaDBlTGcAAAAAAAxVXxZLRXBEbFJYclFsdW0zV084LWgwZUxnAAAAAAAMVWAWS0VwRGxSWHJRbHVtM1dPOC1oMGVMZwAAAAAADFViFktFcERsUlhyUWx1bTNXTzgtaDBlTGcAAAAAAAxVYRZLRXBEbFJYclFsdW0zV084LWgwZUxn",
        "total": 25
    },
    "status": 200,
    "volatile": null
}


$ http POST :7512/app/collection/_search?from=0\&size=1\&scroll=30s $BIO_AUTH
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Tue, 15 May 2018 12:04:23 GMT
Transfer-Encoding: chunked
content-type: application/json

{
    "action": "search",
    "collection": "Timeline",
    "controller": "document",
    "error": null,
    "index": "app-fr-fr",
    "requestId": "854f8ca6-2e20-41db-b72c-50c210c17a78",
    "result": {
        "_scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAADFZ8FktFcERsUlhyUWx1bTNXTzgtaDBlTGcAAAAAAAxWexZLRXBEbFJYclFsdW0zV084LWgwZUxnAAAAAAAMVn0WS0VwRGxSWHJRbHVtM1dPOC1oMGVMZwAAAAAADFZ-FktFcERsUlhyUWx1bTNXTzgtaDBlTGcAAAAAAAxWfxZLRXBEbFJYclFsdW0zV084LWgwZUxn",
        "_shards": {
            "failed": 0,
            "successful": 5,
            "total": 5
        },
        "hits": [
            {
              ...
            }
        ],
        "max_score": 0,
        "timed_out": false,
        "took": 12,
        "total": 529
    },
    "status": 200,
    "volatile": null
}

```

## Context (Environment)
Latest 1.x

### LINKED ISSUE #1125: The security/searchUsers action does not support sorting and aggregations
## Expected Behavior
We should be able to specify aggs and sort parameters in the body of the search and get results sorted or aggregations

## Current Behavior
aggs and sort are not taken into account

## Steps to Reproduce
Call the action with aggs or sort in the body.

## Context (Environment)
Kuzzle 1.2.13

### LINKED ISSUE #1131: "collection:list" returns only the provided collection, if set
## Expected Behavior

Should return all of an index' collections, ignoring the `collection` argument, even if one is provided

## Current Behavior

List only the current collection:

```
$ wscat --connect localhost:7512
connected (press CTRL+C to quit)
> {"controller":"collection","action":"list","index":"foo"}
< {"requestId":"250357c1-37e5-4026-957a-c1be204cf27f","status":200,"error":null,"controller":"collection","action":"list","collection":null,"index":"foo","volatile":null,"result":{"type":"all","collections":[{"name":"bar","type":"stored"},{"name":"baz","type":"stored"},{"name":"qux","type":"stored"}]},"room":"250357c1-37e5-4026-957a-c1be204cf27f"}
> {"controller":"collection","action":"list","index":"foo","collection":"bar"}
< {"requestId":"7b9d39d0-9dff-4d57-8c43-155c78a1ca96","status":200,"error":null,"controller":"collection","action":"list","collection":"bar","index":"foo","volatile":null,"result":{"type":"all","collections":[{"name":"bar","type":"stored"}]},"room":"7b9d39d0-9dff-4d57-8c43-155c78a1ca96"}
> 
```

## Possible Solution

The `listCollections` method in the Elasticsearch service wrapper should remove any `_type` argument set after the `Request` to `esRequest` object conversion.

### LINKED ISSUE #1146: Authentication plugins: missing headers in the request passed to passport
In `login` action, while authenticating through passport, we do not have a `headers` property in the created request object:
https://github.com/kuzzleio/kuzzle/blob/master/lib/api/controllers/authController.js#L85

but some authentication strategies (especially oauth2) need to get data from HTTP headers.

This causes the  following error:
```
"TypeError: Cannot read property 'x-forwarded-proto' of undefined
    at Object.exports.originalURL (..../plugins/available/kuzzle-plugin-auth-passport-oauth/node_modules/passport-oauth2/lib/utils.js:26:27)
    at Strategy.OAuth2Strategy.authenticate (.../plugins/available/kuzzle-plugin-auth-passport-oauth/node_modules/passport-oauth2/lib/strategy.js:141:39)
(...)
```

### LINKED ISSUE #1168: CLI option --port does not seem to have any effect
## Expected Behavior

```
$ bin/kuzzle start --port 7500
$ bin/kuzzle start --port 7501
```

=> should get 2 kuzzle instances, listening to, respectively, ports 7500 and 7501

## Current Behavior

The second start fails with a `EADDRINUSE` error.
I didn't verify it, but I also suspect the 1st instance to listen on 7512 instead of 7500

### LINKED ISSUE #1174: ms and memoryStorage controllers are not treated the same way in security roles
## Expected Behavior

A role granting rights to the `ms` controller should also implicitly grant the same rights to its alias, `memoryStorage`. And vice versa.

## Current Behavior

Kuzzle responds with `ForbiddenError` errors when a user tries to access to the `memoryStorage` controller when his security profile only grants him rights over the `ms` controller.
The reverse is also true.

### PR DESCRIPTION
**Pull request by scottinet**
# [1.5.0](https://github.com/kuzzleio/kuzzle/releases/tag/1.5.0) (2018-09-13)

#### Bug fixes

- [ [#1167](https://github.com/kuzzleio/kuzzle/pull/1167) ] Initialize repositories before plugins   ([Aschen](https://github.com/Aschen))
- [ [#1176](https://github.com/kuzzleio/kuzzle/pull/1176) ] Fix #1174: granting rights to the "ms" controller should also work with its "memoryStorage" alias   ([scottinet](https://github.com/scottinet))
- [ [#1177](https://github.com/kuzzleio/kuzzle/pull/1177) ] Fix #1168: remove useless CLI --port option    ([scottinet](https://github.com/scottinet))
- [ [#1164](https://github.com/kuzzleio/kuzzle/pull/1164) ] Fix swagger invalid output format   ([benoitvidis](https://github.com/benoitvidis))
- [ [#1157](https://github.com/kuzzleio/kuzzle/pull/1157) ] Fix #1131: listCollections limited to the provided collection name, when specified   ([scottinet](https://github.com/scottinet))
- [ [#1162](https://github.com/kuzzleio/kuzzle/pull/1162) ] Fix wrong ES version error message   ([scottinet](https://github.com/scottinet))
- [ [#1153](https://github.com/kuzzleio/kuzzle/pull/1153) ] Fixes #1146, passport login request missing headers   ([benoitvidis](https://github.com/benoitvidis))
- [ [#1154](https://github.com/kuzzleio/kuzzle/pull/1154) ] Prevent a crash when using pre-1.4.0 configuration files   ([scottinet](https://github.com/scottinet))
- [ [#1143](https://github.com/kuzzleio/kuzzle/pull/1143) ] Add action and controller in request input for http events   ([Aschen](https://github.com/Aschen))
- [ [#1144](https://github.com/kuzzleio/kuzzle/pull/1144) ] Fixes #1125 - aggs & sort on user search   ([benoitvidis](https://github.com/benoitvidis))

#### New features

- [ [#1179](https://github.com/kuzzleio/kuzzle/pull/1179) ] KZL-174 Expose to plugins a SDK instance directly mapped to the funnel   ([ballinette](https://github.com/ballinette))
- [ [#1182](https://github.com/kuzzleio/kuzzle/pull/1182) ] KZL 290 - Add fixtures for securities   ([Aschen](https://github.com/Aschen))
- [ [#1129](https://github.com/kuzzleio/kuzzle/pull/1129) ] Add AdminController   ([Aschen](https://github.com/Aschen))

#### Enhancements

- [ [#1191](https://github.com/kuzzleio/kuzzle/pull/1191) ] Update images build script   ([Aschen](https://github.com/Aschen))
- [ [#1181](https://github.com/kuzzleio/kuzzle/pull/1181) ] Plugins/Protocols manifest.json overhaul   ([scottinet](https://github.com/scottinet))
- [ [#1187](https://github.com/kuzzleio/kuzzle/pull/1187) ] Add LGTM code quality badges   ([xcorail](https://github.com/xcorail))
- [ [#1185](https://github.com/kuzzleio/kuzzle/pull/1185) ] KZL 454 - Allow subscribe filters on metadata   ([Aschen](https://github.com/Aschen))
- [ [#1186](https://github.com/kuzzleio/kuzzle/pull/1186) ] KZL 46 - Add metadata to published documents   ([Aschen](https://github.com/Aschen))
- [ [#1178](https://github.com/kuzzleio/kuzzle/pull/1178) ] Use local multi-stage build for kuzzleio/plugin-dev and kuzzleio/kuzzle   ([Aschen](https://github.com/Aschen))
- [ [#1175](https://github.com/kuzzleio/kuzzle/pull/1175) ] Allow to search document with empty query through a HTTP GET request   ([ballinette](https://github.com/ballinette))
- [ [#1173](https://github.com/kuzzleio/kuzzle/pull/1173) ] Fix #1115: Standardize the scrollId return value   ([scottinet](https://github.com/scottinet))
- [ [#1158](https://github.com/kuzzleio/kuzzle/pull/1158) ] Replace ParseError errors with BadRequestError objects   ([scottinet](https://github.com/scottinet))
- [ [#1171](https://github.com/kuzzleio/kuzzle/pull/1171) ] Fix #1015: Add token expiration information to login response   ([scottinet](https://github.com/scottinet))
- [ [#1163](https://github.com/kuzzleio/kuzzle/pull/1163) ] Fix documentation URL in the startup message   ([scottinet](https://github.com/scottinet))
- [ [#1152](https://github.com/kuzzleio/kuzzle/pull/1152) ] Add script to build and push docker images   ([Aschen](https://github.com/Aschen))
- [ [#1155](https://github.com/kuzzleio/kuzzle/pull/1155) ] Inject protocol informations into the RequestContext object   ([scottinet](https://github.com/scottinet))
- [ [#1147](https://github.com/kuzzleio/kuzzle/pull/1147) ] Test Kuzzle against different node LTS versions   ([Aschen](https://github.com/Aschen))
- [ [#1145](https://github.com/kuzzleio/kuzzle/pull/1145) ] Deprecate "constructor" auth option and replace it with "authenticator"   ([scottinet](https://github.com/scottinet))

#### Others

- [ [#1193](https://github.com/kuzzleio/kuzzle/pull/1193) ] Plugins update   ([scottinet](https://github.com/scottinet))
---

### CODE REVIEW

File: lib/api/core/plugins/pluginsManager.js [hunk 1]
```diff
@@ -699,7 +688,7 @@ class PluginsManager {
    * @throws {PluginImplementationError} If strategies registration fails
    */
   _initAuthenticators (plugin) {
-    const errorPrefix = `[${plugin.name}]:`;
+    const errorPrefix = `[${plugin.manifest.name}]:`;
 
     // @todo the _.isNil test need to be removed as soon as the
```
Comment (kuzzle) [inline lib/api/core/plugins/pluginsManager.js]: INFO Complete the task associated to this TODO comment. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS1135)

**Comment by kuzzle** [comment]
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
