### PR TITLE
fixes #1146, passport login request missing headers

### LINKED ISSUE #1146: Authentication plugins: missing headers in the request passed to passport
In `login` action, while authenticating through passport, we do not have a `headers` property in the created request object:
https://github.com/kuzzleio/kuzzle/blob/master/lib/api/controllers/authController.js#L85

but some authentication strategies (especially oauth2) need to get data from HTTP headers.

This causes the  following error:
```
"TypeError: Cannot read property 'x-forwarded-proto' of undefined
    at Object.exports.originalURL (..../plugins/available/kuzzle-plugin-auth-passport-oauth/node_modules/passport-oauth2/lib/utils.js:26:27)
    at Strategy.OAuth2Strategy.authenticate (.../plugins/available/kuzzle-plugin-auth-passport-oauth/node_modules/passport-oauth2/lib/strategy.js:141:39)
(...)
```

### PR DESCRIPTION
**Pull request by benoitvidis**
## What does this PR do ?

Fixes #1146 .
After digging in passport code, I finally found the expected type for the Request is an `http.IncomingMessage`.

### How should this be manually tested?

1. install [kuzzle-plugin-auth-passport-oauth](https://github.com/kuzzleio/kuzzle-plugin-auth-passport-oauth)
2. configure it in kuzzlerc, i.e:
```json
{
  "plugins": {
    "kuzzle-plugin-auth-passport-oauth": {
      "strategies": {
        "github": {
          "credentials": {
            "clientID": "<my client id>",
              "clientSecret": "<my secret>",
              "callbackURL": "http://localhost:8080"
          },
            "persist": [
              "login",
            "avatar_url",
            "name",
            "email"
            ],
            "scope": [
              "email",
            "public_profile"
            ],
            "kuzzleAttributesMapping": {
              "userMail": "email"
            },
            "identifierAttribute": "id"
        }
      },
        "defaultProfiles": [
          "default"
        ]
    }
  }
}
```
3. Test it in your browser:
index.html
```html
<!DOCTYPE html>
<html>
    <head>
      <script src="https://cdn.rawgit.com/kuzzleio/sdk-javascript/master/dist/kuzzle.js"></script>
      <script src="https://cdn.rawgit.com/kuzzleio/kuzzle-sdk-login-oauth-popup/master/index.js"></script>
    </head>
    <body>
        <script>

        </script>
    </body>
</html>
```
in the console:
```js
const k = new Kuzzle('localhost');
k.loginOauthPopup('github')
```

`console.log` anything you want.

NB: no tests, sorry (could not find anything relevant, any input is welcome).

### CODE REVIEW

**Comment by scottinet** [comment]
Does it have to be merged in `master`?

**Comment by ballinette** [comment]
agree with @scottinet : it's a bugfix, but can wait for a future relase (there is a workaround for now)
so it should rather be merged to `1.x`

File: lib/api/controllers/authController.js [hunk 1]
```diff
@@ -26,6 +26,9 @@ const
   _ = require('lodash'),
   User = require('../core/models/security/user'),
   formatProcessing = require('../core/auth/formatProcessing'),
+  {
+    IncomingMessage
+  } = require('http'),
```
Comment (Aschen) [inline lib/api/controllers/authController.js]: Nitpicking: 
Why don't use `IncomingMessage = require('http').IncomingMessage` ? I'm surprised that our linter allow that syntax for single import.

Comment (alexandrebouthinon) [reply lib/api/controllers/authController.js]: It's the ES6 import (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

Comment (scottinet) [reply lib/api/controllers/authController.js]: Nope. It's a [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
Anyway, @Aschen is right, this is not useful to use that syntax when there is only 1 item to extract (and it's a nitpicking issue)

Comment (benoitvidis) [reply lib/api/controllers/authController.js]: Nodejs tends to promote destructured imports even for single inclusions.
cf https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_constructor_new_url_input_base for instance of node.js unit tests on github.

File: lib/api/controllers/authController.js [hunk 2]
```diff
@@ -81,8 +84,23 @@ class AuthController {
     assertArgsHasAttribute(request, 'strategy');
 
     const strategy = request.input.args.strategy;
+    const passportRequest = new IncomingMessage();
+
+    passportRequest.url = `/login?strategy=${strategy}`;
+    passportRequest.method = 'POST';
```
[the remark this answers is not in the document]
Comment (benoitvidis) [reply lib/api/controllers/authController.js]: I'll check if it can be retrieved from the request for http and keep it as POST (and add some comment about it).
The same applies for the url. The idea was just to create an as-valid-as-possible object here.

**Comment by benoitvidis** [comment]
@scottinet you're right. There is a workaround for the issue and can wait for the next release.

File: lib/api/controllers/authController.js (hunk 1 above)
Comment (Aschen) [reply lib/api/controllers/authController.js]: I prefer this syntax too, even for a single import.  
I thought our linter won't allow this because I remember that I had to fix an import like that recently. Maybe it was before Node8 support
