### PR TITLE
Release 1.4.0

### LINKED ISSUE #1125: The security/searchUsers action does not support sorting and aggregations
## Expected Behavior
We should be able to specify aggs and sort parameters in the body of the search and get results sorted or aggregations

## Current Behavior
aggs and sort are not taken into account

## Steps to Reproduce
Call the action with aggs or sort in the body.

## Context (Environment)
Kuzzle 1.2.13

### PR DESCRIPTION
**Pull request by scottinet**
# [1.4.0](https://github.com/kuzzleio/kuzzle/releases/tag/1.4.0) (2018-07-10)

#### Bug fixes

- [ [#1143](https://github.com/kuzzleio/kuzzle/pull/1143) ] Add action and controller in request input for http events   ([Aschen](https://github.com/Aschen))
- [ [#1144](https://github.com/kuzzleio/kuzzle/pull/1144) ] Fixes #1125 - aggs & sort on user search   ([benoitvidis](https://github.com/benoitvidis))

#### New features

- [ [#1129](https://github.com/kuzzleio/kuzzle/pull/1129) ] Add AdminController   ([Aschen](https://github.com/Aschen))

#### Enhancements

- [ [#1147](https://github.com/kuzzleio/kuzzle/pull/1147) ] Test Kuzzle against different node LTS versions   ([Aschen](https://github.com/Aschen))
- [ [#1145](https://github.com/kuzzleio/kuzzle/pull/1145) ] Deprecate "constructor" auth option and replace it with "authenticator"   ([scottinet](https://github.com/scottinet))
---

### CODE REVIEW

File: lib/api/core/plugins/pluginsManager.js [hunk 1]
```diff
@@ -634,24 +679,31 @@ class PluginsManager {
...
+    if (!_.isPlainObject(plugin.object.strategies) || _.isEmpty(plugin.object.strategies)) {
+      throw new PluginImplementationError(`${errorPrefix} the exposed "strategies" plugin property must be a non-empty object`);
     }
 
-    Object.keys(plugin.object.strategies).forEach(strategyName => {
-      const strategy = plugin.object.strategies[strategyName];
-
-      try {
-        this.registerStrategy(plugin.name, strategyName, strategy);
+    // @todo the _.isNil test need to be removed as soon as the
```
Comment (kuzzle) [inline lib/api/core/plugins/pluginsManager.js]: INFO Complete the task associated to this TODO comment. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS1135)

**Comment by kuzzle** [comment]
SonarQube analysis reported 2 issues
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![INFO][INFO] [index.js#L104](https://github.com/kuzzleio/kuzzle/blob/247618b0897d2ae17c86575533ed73f357d32ab8/lib/services/internalEngine/index.js#L104): Complete the task associated to this TODO comment. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
