### PR TITLE
Fix request statistics counters in case of a request failure

### LINKED ISSUE #942: OnGoingRequests of _getAllStats decrements and is negative
When making a _getAllStats query to Kuzzle, the onGoingRequests can be negative:
```json
"ongoingRequests": {
   "websocket": -94,
    "http": 0
}
```

### PR DESCRIPTION
**Pull request by scottinet**
# Description

Fix erroneous request statistics:

* requests possibly being counted as both completed and failed if a pipe on a controller action `onSuccess` event failed
* doubled failed requests counter
* possibly negative ongoing requests counter

# Solved issue

#942

### CODE REVIEW

File: lib/api/controllers/funnelController.js [hunk 1]
```diff
@@ -487,7 +485,6 @@ class FunnelController {
             return Bluebird.reject(modifiedRequest.error);
           })
           .catch(() => {
```
Comment (kuzzle) [inline lib/api/controllers/funnelController.js]: MINOR Remove curly braces and "return" from this arrow function body. [rule](http://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS3524)

**Comment by kuzzle** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'
