### PR TITLE
fixes #1243 - improve validation error messages

### LINKED ISSUE #1243: Improve document validation error message
When validations are in place with a `strict` rule, one might receive this kind of error message:

```
Document: The document validation is strict; it can not add unspecified sub-fields.
```

As a developer, it is very difficult to understand which sub-field is the error referring to and therefore quite hard to fix either the validation or the sent request payload.

## Expected Behavior
A more detailed error message containing:
- The sub-field name that failed the validation (should have)
- The of rule that failed, ie: "expected string got number"  (nice to have)

## Current Behavior
A generic and not very helpful message is returned

## Possible Solution
Do not use validations

## Steps to Reproduce
1. Add a valid specification/validation with a `strict: true` rule
2. Violate that rule when calling any api (ie: create a document)
3. The returned error is the one in the intro

## Context (Environment)
I was writing down validations and when trying it out I have data that seems right for the given validation but it fails. I can't figure out what's the problem from the generic error. I ended up ignoring validations for now.

### PR DESCRIPTION
**Pull request by benoitvidis**
## What does this PR do ?

This PR is a dirty fix for https://github.com/kuzzleio/kuzzle/issues/1243 but I could not figure out any cleaner way to proceed.

### How should this be manually tested?

You can use [this script](https://gist.github.com/benoitvidis/221335b714babdb726ddb07e9128f685)

### Other changes

- rename `validationPromise` to `validate`

### CODE REVIEW

File: lib/api/core/validation/index.js [hunk 1]
```diff
@@ -84,23 +84,23 @@ class Validation {
...
    * @param {Request} request
    * @param {boolean} [verbose]
    * @returns {Promise.<{documentBody: *, errorMessages:string[], valid: boolean}|KuzzleRequest>}
    */
-  validationPromise(request, verbose = false) {
+  validate(request, verbose = false) {
     const
-      id = request.input.resource._id;
+      id = request.input.resource._id,
+      index = request.input.resource.index,
```
Comment (kuzzle) [inline lib/api/core/validation/index.js]: MINOR Use destructuring syntax for these assignments from "request.input.resource". [rule](https://sonarqube.kaliop.net/coding_rules#rule_key=javascript%3AS3514)

**Comment by kuzzle** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
