### PR TITLE
 [cli] Log fixtures import errors

### LINKED ISSUE #1001: The fixtures feature at start does not report errors
When fixtures are imported, no error are reported and it is stated that all documents were imported well.

Way to reproduce: declare a collection a dynamic = strict and try to import document with new fields

### PR DESCRIPTION
**Pull request by benoitvidis**
Fixes #1001

### CODE REVIEW

File: lib/services/elasticsearch.js [hunk 1]
```diff
@@ -679,17 +679,24 @@ class ElasticSearch extends Service {
...
+            if (item.error) {
+              item.action = action;
+              result.partialErrors.push(item);
+            }
+            else {
+              items.push(item);
             }
           }
+
+          result.items = items;
```
Comment (benoitvidis) [inline lib/services/elasticsearch.js]: boyscouting: split valid from errored items in result.items vs result.partialErrors
